import { Sprite } from '../types/sprite';

// Base layer sprites (ground/terrain)
const BASE_LAYER_IDS = [
  'wood1',
  'water1',
  'twig1',
  'tile1',
  'tile2',
  'tile3',
  'stair1',
  'stair2',
  'stair3',
  'sand1',
  'sand2',
  'sand3',
  'sand4',
  'road1',
  'reeds1',
  'plank1',
  'plank2',
  'plank3',
  'moss1',
  'moss2',
  'leaf1',
  'leaf2',
  'leaf3',
  'ground_tile_porous2',
  'ground_tile_porous1',
  'ground_tile_foliage2',
  'ground_tile_foliage1',
  'grass7',
  'grass6',
  'grass5',
  'grass4',
  'grass3',
  'grass2',
  'grass1',
  'brick1',
];

// Helper function to format sprite name
const formatSpriteName = (id: string): string => {
  return id
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .replace(/\d+$/, '')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
    .trim();
};

// Generate base layer sprites
const baseLayerSprites: Sprite[] = BASE_LAYER_IDS.map(id => ({
  id,
  name: formatSpriteName(id),
  imageUrl: `/sprites/${id}.png`,
  layer: 'base' as const,
}));

// Secondary layer sprites (objects/decorations)
const secondaryLayerSprites: Sprite[] = [
  // Animals
  { id: 'agave1', name: 'Agave', imageUrl: '/sprites/agave1.png', layer: 'secondary' },
  { id: 'anthill1', name: 'Anthill', imageUrl: '/sprites/anthill1.png', layer: 'secondary' },
  { id: 'bat1', name: 'Bat', imageUrl: '/sprites/bat1.png', layer: 'secondary' },
  { id: 'bear1', name: 'Bear', imageUrl: '/sprites/bear1.png', layer: 'secondary' },
  { id: 'bee1', name: 'Bee', imageUrl: '/sprites/bee1.png', layer: 'secondary' },
  { id: 'beetle1', name: 'Beetle', imageUrl: '/sprites/beetle1.png', layer: 'secondary' },
  { id: 'bird1', name: 'Bird', imageUrl: '/sprites/bird1.png', layer: 'secondary' },
  { id: 'bird2', name: 'Bird 2', imageUrl: '/sprites/bird2.png', layer: 'secondary' },
  { id: 'bird3', name: 'Bird 3', imageUrl: '/sprites/bird3.png', layer: 'secondary' },
  { id: 'bird4', name: 'Bird 4', imageUrl: '/sprites/bird4.png', layer: 'secondary' },
  { id: 'bird5', name: 'Bird 5', imageUrl: '/sprites/bird5.png', layer: 'secondary' },
  { id: 'bird6', name: 'Bird 6', imageUrl: '/sprites/bird6.png', layer: 'secondary' },
  { id: 'bone1', name: 'Bone', imageUrl: '/sprites/bone1.png', layer: 'secondary' },
  { id: 'butterfly1', name: 'Butterfly', imageUrl: '/sprites/butterfly1.png', layer: 'secondary' },
  { id: 'butterfly2', name: 'Butterfly 2', imageUrl: '/sprites/butterfly2.png', layer: 'secondary' },
  { id: 'cat1', name: 'Cat', imageUrl: '/sprites/cat1.png', layer: 'secondary' },
  { id: 'cat2', name: 'Cat 2', imageUrl: '/sprites/cat2.png', layer: 'secondary' },
  { id: 'cow1', name: 'Cow', imageUrl: '/sprites/cow1.png', layer: 'secondary' },
  { id: 'cow2', name: 'Cow 2', imageUrl: '/sprites/cow2.png', layer: 'secondary' },
  { id: 'coyote1', name: 'Coyote', imageUrl: '/sprites/coyote1.png', layer: 'secondary' },
  { id: 'crab1', name: 'Crab', imageUrl: '/sprites/crab1.png', layer: 'secondary' },
  { id: 'crow1', name: 'Crow', imageUrl: '/sprites/crow1.png', layer: 'secondary' },
  { id: 'deer1', name: 'Deer', imageUrl: '/sprites/deer1.png', layer: 'secondary' },
  { id: 'dog1', name: 'Dog', imageUrl: '/sprites/dog1.png', layer: 'secondary' },
  { id: 'donkey1', name: 'Donkey', imageUrl: '/sprites/donkey1.png', layer: 'secondary' },
  { id: 'duck1', name: 'Duck', imageUrl: '/sprites/duck1.png', layer: 'secondary' },
  { id: 'duck2', name: 'Duck 2', imageUrl: '/sprites/duck2.png', layer: 'secondary' },
  { id: 'fox1', name: 'Fox', imageUrl: '/sprites/fox1.png', layer: 'secondary' },
  { id: 'frog1', name: 'Frog', imageUrl: '/sprites/frog1.png', layer: 'secondary' },
  { id: 'goat1', name: 'Goat', imageUrl: '/sprites/goat1.png', layer: 'secondary' },
  { id: 'goose1', name: 'Goose', imageUrl: '/sprites/goose1.png', layer: 'secondary' },
  { id: 'hedgehog1', name: 'Hedgehog', imageUrl: '/sprites/hedgehog1.png', layer: 'secondary' },
  { id: 'horse1', name: 'Horse', imageUrl: '/sprites/horse1.png', layer: 'secondary' },
  { id: 'lion1', name: 'Lion', imageUrl: '/sprites/lion1.png', layer: 'secondary' },
  { id: 'possum1', name: 'Possum', imageUrl: '/sprites/possum1.png', layer: 'secondary' },
  { id: 'rabbit1', name: 'Rabbit', imageUrl: '/sprites/rabbit1.png', layer: 'secondary' },
  { id: 'rabbit2', name: 'Rabbit 2', imageUrl: '/sprites/rabbit2.png', layer: 'secondary' },
  { id: 'tiger1', name: 'Tiger', imageUrl: '/sprites/tiger1.png', layer: 'secondary' },
  { id: 'weasel1', name: 'Weasel', imageUrl: '/sprites/weasel1.png', layer: 'secondary' },
  { id: 'wolf1', name: 'Wolf', imageUrl: '/sprites/wolf1.png', layer: 'secondary' },

  // Plants & Nature
  { id: 'bamboo1', name: 'Bamboo', imageUrl: '/sprites/bamboo1.png', layer: 'secondary' },
  { id: 'branch1', name: 'Branch', imageUrl: '/sprites/branch1.png', layer: 'secondary' },
  { id: 'branch2', name: 'Branch 2', imageUrl: '/sprites/branch2.png', layer: 'secondary' },
  { id: 'bush1', name: 'Bush', imageUrl: '/sprites/bush1.png', layer: 'secondary' },
  { id: 'bush2', name: 'Bush 2', imageUrl: '/sprites/bush2.png', layer: 'secondary' },
  { id: 'bush3', name: 'Bush 3', imageUrl: '/sprites/bush3.png', layer: 'secondary' },
  { id: 'bush4', name: 'Bush 4', imageUrl: '/sprites/bush4.png', layer: 'secondary' },
  { id: 'cabbage1', name: 'Cabbage', imageUrl: '/sprites/cabbage1.png', layer: 'secondary' },
  { id: 'cactus1', name: 'Cactus', imageUrl: '/sprites/cactus1.png', layer: 'secondary' },
  { id: 'dandelion1', name: 'Dandelion', imageUrl: '/sprites/dandelion1.png', layer: 'secondary' },
  { id: 'flower1', name: 'Flower', imageUrl: '/sprites/flower1.png', layer: 'secondary' },
  { id: 'flower2', name: 'Flower 2', imageUrl: '/sprites/flower2.png', layer: 'secondary' },
  { id: 'flower3', name: 'Flower 3', imageUrl: '/sprites/flower3.png', layer: 'secondary' },
  { id: 'flower4', name: 'Flower 4', imageUrl: '/sprites/flower4.png', layer: 'secondary' },
  { id: 'fruit-tree1', name: 'Fruit Tree', imageUrl: '/sprites/fruit-tree1.png', layer: 'secondary' },
  { id: 'fungus1', name: 'Fungus', imageUrl: '/sprites/fungus1.png', layer: 'secondary' },
  { id: 'houseplant1', name: 'Houseplant', imageUrl: '/sprites/houseplant1.png', layer: 'secondary' },
  { id: 'houseplant2', name: 'Houseplant 2', imageUrl: '/sprites/houseplant2.png', layer: 'secondary' },
  { id: 'houseplant3', name: 'Houseplant 3', imageUrl: '/sprites/houseplant3.png', layer: 'secondary' },
  { id: 'houseplant4', name: 'Houseplant 4', imageUrl: '/sprites/houseplant4.png', layer: 'secondary' },
  { id: 'logs1', name: 'Logs', imageUrl: '/sprites/logs1.png', layer: 'secondary' },
  { id: 'palm1', name: 'Palm', imageUrl: '/sprites/palm1.png', layer: 'secondary' },
  { id: 'palm2', name: 'Palm 2', imageUrl: '/sprites/palm2.png', layer: 'secondary' },
  { id: 'pea1', name: 'Pea', imageUrl: '/sprites/pea1.png', layer: 'secondary' },
  { id: 'pebble1', name: 'Pebble', imageUrl: '/sprites/pebble1.png', layer: 'secondary' },
  { id: 'pebble2', name: 'Pebble 2', imageUrl: '/sprites/pebble2.png', layer: 'secondary' },
  { id: 'pine1', name: 'Pine', imageUrl: '/sprites/pine1.png', layer: 'secondary' },
  { id: 'pine2', name: 'Pine 2', imageUrl: '/sprites/pine2.png', layer: 'secondary' },
  { id: 'pumpkin1', name: 'Pumpkin', imageUrl: '/sprites/pumpkin1.png', layer: 'secondary' },
  { id: 'radish1', name: 'Radish', imageUrl: '/sprites/radish1.png', layer: 'secondary' },
  { id: 'reed2', name: 'Reed', imageUrl: '/sprites/reed2.png', layer: 'secondary' },
  { id: 'rock1', name: 'Rock', imageUrl: '/sprites/rock1.png', layer: 'secondary' },
  { id: 'rock2', name: 'Rock 2', imageUrl: '/sprites/rock2.png', layer: 'secondary' },
  { id: 'rock3', name: 'Rock 3', imageUrl: '/sprites/rock3.png', layer: 'secondary' },
  { id: 'rose1', name: 'Rose', imageUrl: '/sprites/rose1.png', layer: 'secondary' },
  { id: 'seed1', name: 'Seed', imageUrl: '/sprites/seed1.png', layer: 'secondary' },
  { id: 'sprouts1', name: 'Sprouts', imageUrl: '/sprites/sprouts1.png', layer: 'secondary' },
  { id: 'squash1', name: 'Squash', imageUrl: '/sprites/squash1.png', layer: 'secondary' },
  { id: 'squash2', name: 'Squash 2', imageUrl: '/sprites/squash2.png', layer: 'secondary' },
  { id: 'stump1', name: 'Stump', imageUrl: '/sprites/stump1.png', layer: 'secondary' },
  { id: 'sun1', name: 'Sun', imageUrl: '/sprites/sun1.png', layer: 'secondary' },
  { id: 'sun2', name: 'Sun 2', imageUrl: '/sprites/sun2.png', layer: 'secondary' },
  { id: 'sun3', name: 'Sun 3', imageUrl: '/sprites/sun3.png', layer: 'secondary' },
  { id: 'tomato1', name: 'Tomato', imageUrl: '/sprites/tomato1.png', layer: 'secondary' },
  { id: 'tree1', name: 'Tree', imageUrl: '/sprites/tree1.png', layer: 'secondary' },
  { id: 'tree2', name: 'Tree 2', imageUrl: '/sprites/tree2.png', layer: 'secondary' },
  { id: 'tree3', name: 'Tree 3', imageUrl: '/sprites/tree3.png', layer: 'secondary' },
  { id: 'tree4', name: 'Tree 4', imageUrl: '/sprites/tree4.png', layer: 'secondary' },
  { id: 'tree5', name: 'Tree 5', imageUrl: '/sprites/tree5.png', layer: 'secondary' },
  { id: 'tropical1', name: 'Tropical', imageUrl: '/sprites/tropical1.png', layer: 'secondary' },
  { id: 'tropical2', name: 'Tropical 2', imageUrl: '/sprites/tropical2.png', layer: 'secondary' },
  { id: 'tropical3', name: 'Tropical 3', imageUrl: '/sprites/tropical3.png', layer: 'secondary' },
  { id: 'twig2', name: 'Twig 2', imageUrl: '/sprites/twig2.png', layer: 'secondary' },
  { id: 'vine1', name: 'Vine', imageUrl: '/sprites/vine1.png', layer: 'secondary' },

  // Buildings & Structures
  { id: 'arch1', name: 'Arch', imageUrl: '/sprites/arch1.png', layer: 'secondary' },
  { id: 'barrier1', name: 'Barrier', imageUrl: '/sprites/barrier1.png', layer: 'secondary' },
  { id: 'barrier2', name: 'Barrier 2', imageUrl: '/sprites/barrier2.png', layer: 'secondary' },
  { id: 'castle1', name: 'Castle', imageUrl: '/sprites/castle1.png', layer: 'secondary' },
  { id: 'cellar1', name: 'Cellar', imageUrl: '/sprites/cellar1.png', layer: 'secondary' },
  { id: 'cement-pipe1', name: 'Cement Pipe', imageUrl: '/sprites/cement-pipe1.png', layer: 'secondary' },
  { id: 'cinderblock1', name: 'Cinderblock', imageUrl: '/sprites/cinderblock1.png', layer: 'secondary' },
  { id: 'column1', name: 'Column', imageUrl: '/sprites/column1.png', layer: 'secondary' },
  { id: 'dumpster1', name: 'Dumpster', imageUrl: '/sprites/dumpster1.png', layer: 'secondary' },
  { id: 'elevator1', name: 'Elevator', imageUrl: '/sprites/elevator1.png', layer: 'secondary' },
  { id: 'gate1', name: 'Gate', imageUrl: '/sprites/gate1.png', layer: 'secondary' },
  { id: 'greenhouse1', name: 'Greenhouse', imageUrl: '/sprites/greenhouse1.png', layer: 'secondary' },
  { id: 'house1', name: 'House', imageUrl: '/sprites/house1.png', layer: 'secondary' },
  { id: 'house2', name: 'House 2', imageUrl: '/sprites/house2.png', layer: 'secondary' },
  { id: 'house3', name: 'House 3', imageUrl: '/sprites/house3.png', layer: 'secondary' },
  { id: 'ladder1', name: 'Ladder', imageUrl: '/sprites/ladder1.png', layer: 'secondary' },
  { id: 'manhole1', name: 'Manhole', imageUrl: '/sprites/manhole1.png', layer: 'secondary' },
  { id: 'memorial1', name: 'Memorial', imageUrl: '/sprites/memorial1.png', layer: 'secondary' },
  { id: 'milemarker1', name: 'Milemarker', imageUrl: '/sprites/milemarker1.png', layer: 'secondary' },
  { id: 'monument1', name: 'Monument', imageUrl: '/sprites/monument1.png', layer: 'secondary' },
  { id: 'monument2', name: 'Monument 2', imageUrl: '/sprites/monument2.png', layer: 'secondary' },
  { id: 'monument3', name: 'Monument 3', imageUrl: '/sprites/monument3.png', layer: 'secondary' },
  { id: 'outdoor-light1', name: 'Outdoor Light', imageUrl: '/sprites/outdoor-light1.png', layer: 'secondary' },
  { id: 'path1', name: 'Path', imageUrl: '/sprites/path1.png', layer: 'secondary' },
  { id: 'pier1', name: 'Pier', imageUrl: '/sprites/pier1.png', layer: 'secondary' },
  { id: 'pole1', name: 'Pole', imageUrl: '/sprites/pole1.png', layer: 'secondary' },
  { id: 'pyramid1', name: 'Pyramid', imageUrl: '/sprites/pyramid1.png', layer: 'secondary' },
  { id: 'pyramid2', name: 'Pyramid 2', imageUrl: '/sprites/pyramid2.png', layer: 'secondary' },
  { id: 'pyramid3', name: 'Pyramid 3', imageUrl: '/sprites/pyramid3.png', layer: 'secondary' },
  { id: 'rail1', name: 'Rail', imageUrl: '/sprites/rail1.png', layer: 'secondary' },
  { id: 'rubble1', name: 'Rubble', imageUrl: '/sprites/rubble1.png', layer: 'secondary' },
  { id: 'rubble2', name: 'Rubble 2', imageUrl: '/sprites/rubble2.png', layer: 'secondary' },
  { id: 'satellite-dish1', name: 'Satellite Dish', imageUrl: '/sprites/satellite-dish1.png', layer: 'secondary' },
  { id: 'satellite1', name: 'Satellite', imageUrl: '/sprites/satellite1.png', layer: 'secondary' },
  { id: 'satellite2', name: 'Satellite 2', imageUrl: '/sprites/satellite2.png', layer: 'secondary' },
  { id: 'silo1', name: 'Silo', imageUrl: '/sprites/silo1.png', layer: 'secondary' },
  { id: 'slate1', name: 'Slate', imageUrl: '/sprites/slate1.png', layer: 'secondary' },
  { id: 'stair4', name: 'Stair 4', imageUrl: '/sprites/stair4.png', layer: 'secondary' },
  { id: 'streetlight1', name: 'Streetlight', imageUrl: '/sprites/streetlight1.png', layer: 'secondary' },
  { id: 'streetlight2', name: 'Streetlight 2', imageUrl: '/sprites/streetlight2.png', layer: 'secondary' },
  { id: 'telephone-booth1', name: 'Telephone Booth', imageUrl: '/sprites/telephone-booth1.png', layer: 'secondary' },
  { id: 'telescope1', name: 'Telescope', imageUrl: '/sprites/telescope1.png', layer: 'secondary' },
  { id: 'tent1', name: 'Tent', imageUrl: '/sprites/tent1.png', layer: 'secondary' },
  { id: 'tent2', name: 'Tent 2', imageUrl: '/sprites/tent2.png', layer: 'secondary' },
  { id: 'tire1', name: 'Tire', imageUrl: '/sprites/tire1.png', layer: 'secondary' },
  { id: 'tomb1', name: 'Tomb', imageUrl: '/sprites/tomb1.png', layer: 'secondary' },
  { id: 'tower1', name: 'Tower', imageUrl: '/sprites/tower1.png', layer: 'secondary' },
  { id: 'track1', name: 'Track', imageUrl: '/sprites/track1.png', layer: 'secondary' },
  { id: 'traffic-circle1', name: 'Traffic Circle', imageUrl: '/sprites/traffic-circle1.png', layer: 'secondary' },
  { id: 'traffic-sign1', name: 'Traffic Sign', imageUrl: '/sprites/traffic-sign1.png', layer: 'secondary' },
  { id: 'trashcan1', name: 'Trashcan', imageUrl: '/sprites/trashcan1.png', layer: 'secondary' },
  { id: 'turret1', name: 'Turret', imageUrl: '/sprites/turret1.png', layer: 'secondary' },
  { id: 'umbrella1', name: 'Umbrella', imageUrl: '/sprites/umbrella1.png', layer: 'secondary' },
  { id: 'well1', name: 'Well', imageUrl: '/sprites/well1.png', layer: 'secondary' },
  { id: 'window1', name: 'Window', imageUrl: '/sprites/window1.png', layer: 'secondary' },

  // Furniture & Items
  { id: 'bag1', name: 'Bag', imageUrl: '/sprites/bag1.png', layer: 'secondary' },
  { id: 'balloon1', name: 'Balloon', imageUrl: '/sprites/balloon1.png', layer: 'secondary' },
  { id: 'bathtub1', name: 'Bathtub', imageUrl: '/sprites/bathtub1.png', layer: 'secondary' },
  { id: 'bed1', name: 'Bed', imageUrl: '/sprites/bed1.png', layer: 'secondary' },
  { id: 'bench1', name: 'Bench', imageUrl: '/sprites/bench1.png', layer: 'secondary' },
  { id: 'bicycle1', name: 'Bicycle', imageUrl: '/sprites/bicycle1.png', layer: 'secondary' },
  { id: 'bike-rack1', name: 'Bike Rack', imageUrl: '/sprites/bike-rack1.png', layer: 'secondary' },
  { id: 'book1', name: 'Book', imageUrl: '/sprites/book1.png', layer: 'secondary' },
  { id: 'book2', name: 'Book 2', imageUrl: '/sprites/book2.png', layer: 'secondary' },
  { id: 'book3', name: 'Book 3', imageUrl: '/sprites/book3.png', layer: 'secondary' },
  { id: 'bookshelf1', name: 'Bookshelf', imageUrl: '/sprites/bookshelf1.png', layer: 'secondary' },
  { id: 'bowl1', name: 'Bowl', imageUrl: '/sprites/bowl1.png', layer: 'secondary' },
  { id: 'box1', name: 'Box', imageUrl: '/sprites/box1.png', layer: 'secondary' },
  { id: 'broom1', name: 'Broom', imageUrl: '/sprites/broom1.png', layer: 'secondary' },
  { id: 'bubble1', name: 'Bubble', imageUrl: '/sprites/bubble1.png', layer: 'secondary' },
  { id: 'calculator1', name: 'Calculator', imageUrl: '/sprites/calculator1.png', layer: 'secondary' },
  { id: 'campfire1', name: 'Campfire', imageUrl: '/sprites/campfire1.png', layer: 'secondary' },
  { id: 'canoe1', name: 'Canoe', imageUrl: '/sprites/canoe1.png', layer: 'secondary' },
  { id: 'card1', name: 'Card', imageUrl: '/sprites/card1.png', layer: 'secondary' },
  { id: 'carrot1', name: 'Carrot', imageUrl: '/sprites/carrot1.png', layer: 'secondary' },
  { id: 'caution-sign1', name: 'Caution Sign', imageUrl: '/sprites/caution-sign1.png', layer: 'secondary' },
  { id: 'chair1', name: 'Chair', imageUrl: '/sprites/chair1.png', layer: 'secondary' },
  { id: 'chair2', name: 'Chair 2', imageUrl: '/sprites/chair2.png', layer: 'secondary' },
  { id: 'chair3', name: 'Chair 3', imageUrl: '/sprites/chair3.png', layer: 'secondary' },
  { id: 'chest1', name: 'Chest', imageUrl: '/sprites/chest1.png', layer: 'secondary' },
  { id: 'clock1', name: 'Clock', imageUrl: '/sprites/clock1.png', layer: 'secondary' },
  { id: 'cloud1', name: 'Cloud', imageUrl: '/sprites/cloud1.png', layer: 'secondary' },
  { id: 'cloud2', name: 'Cloud 2', imageUrl: '/sprites/cloud2.png', layer: 'secondary' },
  { id: 'cloud3', name: 'Cloud 3', imageUrl: '/sprites/cloud3.png', layer: 'secondary' },
  { id: 'cloud4', name: 'Cloud 4', imageUrl: '/sprites/cloud4.png', layer: 'secondary' },
  { id: 'coin1', name: 'Coin', imageUrl: '/sprites/coin1.png', layer: 'secondary' },
  { id: 'cone1', name: 'Cone', imageUrl: '/sprites/cone1.png', layer: 'secondary' },
  { id: 'cone2', name: 'Cone 2', imageUrl: '/sprites/cone2.png', layer: 'secondary' },
  { id: 'cookiejar1', name: 'Cookie Jar', imageUrl: '/sprites/cookiejar1.png', layer: 'secondary' },
  { id: 'couch1', name: 'Couch', imageUrl: '/sprites/couch1.png', layer: 'secondary' },
  { id: 'crown1', name: 'Crown', imageUrl: '/sprites/crown1.png', layer: 'secondary' },
  { id: 'curtains1', name: 'Curtains', imageUrl: '/sprites/curtains1.png', layer: 'secondary' },
  { id: 'cushion1', name: 'Cushion', imageUrl: '/sprites/cushion1.png', layer: 'secondary' },
  { id: 'desk1', name: 'Desk', imageUrl: '/sprites/desk1.png', layer: 'secondary' },
  { id: 'dice1', name: 'Dice', imageUrl: '/sprites/dice1.png', layer: 'secondary' },
  { id: 'dirt1', name: 'Dirt', imageUrl: '/sprites/dirt1.png', layer: 'secondary' },
  { id: 'doll1', name: 'Doll', imageUrl: '/sprites/doll1.png', layer: 'secondary' },
  { id: 'door1', name: 'Door', imageUrl: '/sprites/door1.png', layer: 'secondary' },
  { id: 'dress1', name: 'Dress', imageUrl: '/sprites/dress1.png', layer: 'secondary' },
  { id: 'dresser1', name: 'Dresser', imageUrl: '/sprites/dresser1.png', layer: 'secondary' },
  { id: 'drink1', name: 'Drink', imageUrl: '/sprites/drink1.png', layer: 'secondary' },
  { id: 'drum1', name: 'Drum', imageUrl: '/sprites/drum1.png', layer: 'secondary' },
  { id: 'dust1', name: 'Dust', imageUrl: '/sprites/dust1.png', layer: 'secondary' },
  { id: 'dust2', name: 'Dust 2', imageUrl: '/sprites/dust2.png', layer: 'secondary' },
  { id: 'ear1', name: 'Ear', imageUrl: '/sprites/ear1.png', layer: 'secondary' },
  { id: 'egg1', name: 'Egg', imageUrl: '/sprites/egg1.png', layer: 'secondary' },
  { id: 'egg2', name: 'Egg 2', imageUrl: '/sprites/egg2.png', layer: 'secondary' },
  { id: 'eggplant1', name: 'Eggplant', imageUrl: '/sprites/eggplant1.png', layer: 'secondary' },
  { id: 'envelope1', name: 'Envelope', imageUrl: '/sprites/envelope1.png', layer: 'secondary' },
  { id: 'eye1', name: 'Eye', imageUrl: '/sprites/eye1.png', layer: 'secondary' },
  { id: 'feather1', name: 'Feather', imageUrl: '/sprites/feather1.png', layer: 'secondary' },
  { id: 'fire-extinguisher1', name: 'Fire Extinguisher', imageUrl: '/sprites/fire-extinguisher1.png', layer: 'secondary' },
  { id: 'fire-hydrant1', name: 'Fire Hydrant', imageUrl: '/sprites/fire-hydrant1.png', layer: 'secondary' },
  { id: 'fire1', name: 'Fire', imageUrl: '/sprites/fire1.png', layer: 'secondary' },
  { id: 'gas-can1', name: 'Gas Can', imageUrl: '/sprites/gas-can1.png', layer: 'secondary' },
  { id: 'ghost1', name: 'Ghost', imageUrl: '/sprites/ghost1.png', layer: 'secondary' },
  { id: 'globe1', name: 'Globe', imageUrl: '/sprites/globe1.png', layer: 'secondary' },
  { id: 'hammer1', name: 'Hammer', imageUrl: '/sprites/hammer1.png', layer: 'secondary' },
  { id: 'hoop1', name: 'Hoop', imageUrl: '/sprites/hoop1.png', layer: 'secondary' },
  { id: 'hose1', name: 'Hose', imageUrl: '/sprites/hose1.png', layer: 'secondary' },
  { id: 'lamp1', name: 'Lamp', imageUrl: '/sprites/lamp1.png', layer: 'secondary' },
  { id: 'lamp2', name: 'Lamp 2', imageUrl: '/sprites/lamp2.png', layer: 'secondary' },
  { id: 'laptop1', name: 'Laptop', imageUrl: '/sprites/laptop1.png', layer: 'secondary' },
  { id: 'laundry1', name: 'Laundry', imageUrl: '/sprites/laundry1.png', layer: 'secondary' },
  { id: 'mop1', name: 'Mop', imageUrl: '/sprites/mop1.png', layer: 'secondary' },
  { id: 'mug1', name: 'Mug', imageUrl: '/sprites/mug1.png', layer: 'secondary' },
  { id: 'nest1', name: 'Nest', imageUrl: '/sprites/nest1.png', layer: 'secondary' },
  { id: 'paper1', name: 'Paper', imageUrl: '/sprites/paper1.png', layer: 'secondary' },
  { id: 'pencil1', name: 'Pencil', imageUrl: '/sprites/pencil1.png', layer: 'secondary' },
  { id: 'pencil2', name: 'Pencil 2', imageUrl: '/sprites/pencil2.png', layer: 'secondary' },
  { id: 'person1', name: 'Person', imageUrl: '/sprites/person1.png', layer: 'secondary' },
  { id: 'person2', name: 'Person 2', imageUrl: '/sprites/person2.png', layer: 'secondary' },
  { id: 'person3', name: 'Person 3', imageUrl: '/sprites/person3.png', layer: 'secondary' },
  { id: 'person4', name: 'Person 4', imageUrl: '/sprites/person4.png', layer: 'secondary' },
  { id: 'person5', name: 'Person 5', imageUrl: '/sprites/person5.png', layer: 'secondary' },
  { id: 'person6', name: 'Person 6', imageUrl: '/sprites/person6.png', layer: 'secondary' },
  { id: 'power1', name: 'Power', imageUrl: '/sprites/power1.png', layer: 'secondary' },
  { id: 'present1', name: 'Present', imageUrl: '/sprites/present1.png', layer: 'secondary' },
  { id: 'puddle1', name: 'Puddle', imageUrl: '/sprites/puddle1.png', layer: 'secondary' },
  { id: 'puddle2', name: 'Puddle 2', imageUrl: '/sprites/puddle2.png', layer: 'secondary' },
  { id: 'puddle3', name: 'Puddle 3', imageUrl: '/sprites/puddle3.png', layer: 'secondary' },
  { id: 'pump1', name: 'Pump', imageUrl: '/sprites/pump1.png', layer: 'secondary' },
  { id: 'sandal1', name: 'Sandal', imageUrl: '/sprites/sandal1.png', layer: 'secondary' },
  { id: 'shoe1', name: 'Shoe', imageUrl: '/sprites/shoe1.png', layer: 'secondary' },
  { id: 'stool1', name: 'Stool', imageUrl: '/sprites/stool1.png', layer: 'secondary' },
  { id: 'stop-sign1', name: 'Stop Sign', imageUrl: '/sprites/stop-sign1.png', layer: 'secondary' },
  { id: 'teddybear1', name: 'Teddybear', imageUrl: '/sprites/teddybear1.png', layer: 'secondary' },
  { id: 'toilet1', name: 'Toilet', imageUrl: '/sprites/toilet1.png', layer: 'secondary' },
  { id: 'trash1', name: 'Trash', imageUrl: '/sprites/trash1.png', layer: 'secondary' },
  { id: 'grave1', name: 'Grave', imageUrl: '/sprites/grave1.png', layer: 'secondary' },
  { id: 'grave2', name: 'Grave 2', imageUrl: '/sprites/grave2.png', layer: 'secondary' },
];

// Combine all sprites
export const SPRITES: Sprite[] = [...baseLayerSprites, ...secondaryLayerSprites];
